apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ticketflow
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort         # external access — gets a public IP